name: Build Unsigned macOS App

on:
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  build:
    runs-on: macos-14

    steps:
      # 1. Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Select the stable Xcode 15.4 environment
      - name: Select Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          brew install swiftlint
          brew install go

      # 4. Build the .app with the correct scheme name
      - name: Build unsigned .app
        run: |
          xcodebuild build \
            -scheme "WireGuardmacOS" \
            -project "WireGuard.xcodeproj" \
            -sdk macosx \
            -configuration Release \
            -derivedDataPath ./build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      # 5. Upload the final .app file as a downloadable artifact
      - name: Upload .app Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WireGuard-macOS-unsigned
          path: build/Build/Products/Release/WireGuard.app