name: Archive macOS App

on:
  workflow_dispatch:

jobs:
  archive:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Install Dependencies
        run: |
          brew install swiftlint
          brew install go

      - name: Create Developer Config File
        run: cp Sources/WireGuardApp/Config/Developer.xcconfig.template Sources/WireGuardApp/Config/Developer.xcconfig

      # (关键改动) 执行 archive 操作，而不是 build
      - name: Archive the project
        run: |
          xcodebuild archive \
            -scheme "WireGuardmacOS" \
            -project "WireGuard.xcodeproj" \
            -configuration Release \
            -archivePath ./build/CyberGuard.xcarchive \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES

      # 将生成的 .xcarchive 文件压缩并上传
      - name: Zip and Upload Archive
        run: |
          cd build/
          zip -r ../CyberGuard.xcarchive.zip CyberGuard.xcarchive
          cd ..
        
      - name: Upload Zipped .xcarchive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberGuard-macOS-archive
          path: CyberGuard.xcarchive.zip