name: Build Ad-Hoc Signed macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 选择稳定的 Xcode
      - name: Select Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      # 3. 安装依赖
      - name: Install Dependencies
        run: |
          brew install swiftlint
          brew install go

      # 4. 创建所需的开发者配置文件
      - name: Create Developer Config File
        run: cp Sources/WireGuardApp/Config/Developer.xcconfig.template Sources/WireGuardApp/Config/Developer.xcconfig

      # 5. (关键修复) 使用 Ad-Hoc 签名进行构建
      - name: Build Ad-Hoc signed .app
        run: |
          xcodebuild build \
            -scheme "WireGuardmacOS" \
            -project "WireGuard.xcodeproj" \
            -sdk macosx \
            -configuration Release \
            -derivedDataPath ./build \
            CODE_SIGN_IDENTITY="-"

      # 6. 手动将构建好的 .app 文件夹压缩
      - name: Zip the .app bundle
        run: |
          cd build/Build/Products/Release/
          zip -r ../../../../CyberGuard-macOS.zip CyberGuard.app
          cd ../../../../

      # 7. 上传我们手动创建的 .zip 文件
      - name: Upload Zipped .app Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberGuard-macOS-ad-hoc-signed
          path: CyberGuard-macOS.zip