name: Build and Package Unsigned macOS App

on:
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-package:
    runs-on: macos-14

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 选择稳定的 Xcode 15.4
      - name: Select Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      # 3. 安装依赖
      - name: Install Dependencies
        run: |
          brew install swiftlint
          brew install go

      # 4. 创建所需的开发者配置文件
      - name: Create Developer Config File
        run: cp Sources/WireGuardApp/Config/Developer.xcconfig.template Sources/WireGuardApp/Config/Developer.xcconfig

      # 5. 构建应用
      - name: Build unsigned .app
        run: |
          xcodebuild build \
            -scheme "WireGuardmacOS" \
            -project "WireGuard.xcodeproj" \
            -sdk macosx \
            -configuration Release \
            -derivedDataPath ./build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      # 6. (关键修复) 手动将构建好的 .app 文件夹压缩
      - name: Zip the .app bundle
        run: |
          # 进入到包含 .app 的目录
          cd build/Build/Products/Release/
          # 使用 zip 命令递归地打包 CyberGuard.app 文件夹
          zip -r ../../../../CyberGuard-macOS.zip CyberGuard.app
          cd ../../../../

      # 7. 上传我们手动创建的 .zip 文件
      - name: Upload Zipped .app Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberGuard-macOS-unsigned
          path: CyberGuard-macOS.zip