name: List Project Schemes

on:
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  list_schemes:
    runs-on: macos-14 # Use the same runner for consistency

    steps:
      # 1. Check out the repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Select the stable Xcode 15.4 environment
      - name: Select Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      # 3. The only important step: List all schemes in the project
      - name: List Available Schemes
        run: xcodebuild -list -project WireGuard.xcodeproj